### ISSUE TITLE
很美观啊，特别适合做展示和插图，谢谢作者

### ISSUE THREAD

**Issue by kaleai** [brickyang/reading-card-generator#1]
从配图就看出了作者真的很细心啊，效果很细腻，很厉害。

**Comment by brickyang** [comment]
谢谢。因为出发点是为了给微信配图，需求比较明确，所以很多地方都写死了，功能很单一。接下来也想多收集一些意见，进一步增加功能。

**Comment by kaleai** [comment]
嗯嗯，您说的是微信公众号么，感觉是很合适的。
