### ISSUE TITLE
能否 把图片画质 再提高点啊？

### ISSUE THREAD

**Issue by Popxie** [brickyang/reading-card-generator#3]
我平常比较喜欢摄影  刚用了下你的项目  上传再下载以后 发现图片质量有下降，我感觉从用户的角度来看的话，这地方不需要降低图片的质量吧? 个人观点 望采纳~  再次感谢楼主的好帖子~

**Comment by brickyang** [comment]
画质倒没有故意降低，只是因为懒 + 目前感觉够用，所以暂时没有做太多处理。通常下载的文件在 1000px 左右，在手机屏幕上看的话，应该是可以接受的。

这个项目刚做了几个小时，做完功能就先放上来了，容我逐步改进。

**Comment by Popxie** [comment]
好的好的  持续关注你~
