### ISSUE TITLE
应该可以不通过下载工程，直接用github仓库做一个在线链接就可使用的吧

### ISSUE THREAD

**Issue by kaleai** [brickyang/reading-card-generator#4]
想提一个优化点，能否给出一个在线的链接，这样方便作为一个在线工具来使用。

**Comment by kaleai** [comment]
链接地址如：http://brickyang.github.io/reading-card-generator

**Comment by brickyang** [comment]
可以的。

只是一开始的出发点只是内部小工具，没计划提供在线工具。如果真的有用我就放上去。
